### ISSUE TITLE
Confuse about some parameters

### ISSUE THREAD

**Issue by hirorogithub** [ENCP/CNNdroid#12]
When i writing net structure file about caffe-to-Cnndroid, i find some parameters that never appear in caffe`s   net structure files but in CNNdroid`s,like normalization region,group.And i also confuse that i can`t find layer type like dropout layers.
Could you tell what these parameters means?I'm afraid it was a bother for you to do this. I would be very greatful if you can give me a hand.

**Comment by latifisalar** [comment]
Hi,
Group is used in convolution layer and in the AlexNet because of the multi-GPU tuning method they had proposed, you can just use a value of 1 for the other networks.
Normalization region is also only used in LRN layer which is present in the AlexNet but not in the other CNNs.
Dropout layer is used in the training phase, but CNNdroid is only meant to be used to run CNNs in the test phase, that's why it's not available in the library.

**Comment by hirorogithub** [comment]
Thanks for your help!
